name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install yarn and pkg
        run: |
          npm install -g yarn
          npm install -g pkg

      - name: Clone electron/asar and prepare
        run: |
          git clone git@github.com:electron/asar.git
          cd asar
          yarn install

      - name: Determine eleron/asar package version through package.json
        id: asar-version
        run: |
          cd asar
          echo "::set-output name=version::$(node -p "require('./package.json').version")"
